CREATE TABLE [dbo].[Clinician]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[HCPId] NVARCHAR(50) NOT NULL,
	[Password] NVARCHAR(50) NOT NULL
)

GO

CREATE UNIQUE INDEX [Unique_HCPId] ON [dbo].[Clinician] ([HCPId])